# Generated by Django 4.0.3 on 2022-04-06 14:09

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='(Max 45 Characters)', max_length=45)),
                ('Surname', models.CharField(blank=True, help_text='(Max 45 Characters)', max_length=45)),
                ('No_of_Pages', models.IntegerField(choices=[(36, 36), (60, 60)])),
                ('PAN', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('[A-Z]{5}[0-9]{4}[A-Z]{1}', message='Enter a Valid PAN Number')])),
                ('Aadhaar_Number', models.CharField(help_text='Enter Aadhaar with requried spaces', max_length=500, null=True, validators=[django.core.validators.RegexValidator('^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$', message='Enter a Valid Aadhar Number')])),
                ('Gender', models.CharField(max_length=500)),
                ('Date_of_Birth', models.DateField()),
                ('Place_of_Birth', models.CharField(help_text='Village/City/Town', max_length=500)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Marital_Status', models.CharField(choices=[('Widow/Widower', 'Widow/Widower'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Seperated', 'Seperated')], max_length=100)),
                ('Citizenship_of_India', models.CharField(max_length=255)),
                ('Employment_Type', models.CharField(choices=[('Governnment', 'Government'), ('Statutory Body', 'Statutory Body'), ('Private', 'Private'), ('Homemaker', 'Homemaker'), ('Not Employed', 'Not Employed'), ('Others', 'Others'), ('PSU', 'PSU'), ('Retired Government Servent', 'Retired Government Servent'), ('Student', 'Student'), ('Self Employed', 'Self Employed'), ('Retired-Private Service', 'Retired-Private Service'), ('Owners Partners & Directors of Companies Which Are Members Of Cli Ficci & Assocham', 'Owners Partners & Directors of Companies Which Are Members Of Cli Ficci & Assocham')], max_length=500)),
                ('Government_Servant', models.BooleanField(default=False)),
                ('Educational_Qualification', models.CharField(choices=[('Graduate and Above', 'Graduate and Above'), ('7th Pass or Less', '7th Pass or Less'), ('10th Pass or Above', '10th Pass or Above'), ('Between 8th and 9th Standard', 'Between 8th and 9th Standard')], max_length=500)),
                ('Non_ECR_Category', models.BooleanField(default=False)),
                ('Visible_Distinguishing_Mark', models.CharField(blank=True, max_length=100)),
                ('Application_Status', models.CharField(choices=[('In Queue', 'In Queue'), ('Processed and Approved', 'Processed and Approved'), ('Cancelled', 'Cancelled')], max_length=200)),
                ('Application_Id', models.PositiveBigIntegerField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Name', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
