# Generated by Django 4.0.3 on 2022-04-03 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_Pages', models.IntegerField(choices=[(36, 36), (60, 60)])),
                ('PAN_Card', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('[A-Z]{5}[0-9]{4}[A-Z]{1}', message='Enter a Valid PAN Number')])),
                ('Aadhaar_Card', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$', message='Enter a Valid Aadhar Number')])),
                ('Gender', models.CharField(max_length=500)),
                ('Date_of_Birth', models.DateField(max_length=8)),
                ('Alias_Names', models.BooleanField(blank=True, default=False, null=True)),
                ('Name_Change', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
