# Generated by Django 4.0.3 on 2022-04-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_passport_date_of_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Passport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.passport'),
        ),
    ]
