# Generated by Django 4.0.3 on 2022-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_document_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='Remark',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
